name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    required: true
    description: 'github token which has access to push'
  origin:
    required: false
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  only:
    required: false
    description: 'the branches to copy'
  exclude:
    required: false
    description: 'the excluded branches to copy'
runs:
  using: 'node12'
  main: 'dist/index.js'
