name: 'fork-sync-all-branches'
description: 'a action to sync (reset) all branches with upstream'
author: 'anatawa12'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  github_token:
    required: true
    description: 'github token which has access to push'
  origin:
    required: false
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  only:
    required: false
    description: 'the branches to copy'
  exclude:
    required: false
    description: 'the excluded branches to copy'
runs:
  using: 'node12'
  main: 'dist/index.js'
